package managedfile

import (
	"encoding/json"
	"fmt"
	"os"
	"time"
)

// BackupRecord is the retention metadata for one durable pre-mutation copy. It
// carries the digest of the copied bytes so recovery can prove it restored
// exactly what the operation captured, and the operation that owns it so a
// full uninstall can keep referenced backups and drop unreferenced ones.
type BackupRecord struct {
	Source      string    `json:"source"`
	Path        string    `json:"path"`
	Digest      string    `json:"digest"`
	Size        int64     `json:"size"`
	Mode        uint32    `json:"mode"`
	OperationID string    `json:"operation_id,omitempty"`
	Created     time.Time `json:"created"`
}

// BackupFile copies src to dest, fsyncing the bytes and the containing
// directory before returning. The copy is written through WriteFileAtomic, so
// dest never observes a partial backup. A missing source is an error: an
// operation with nothing to back up records no backup at all.
func BackupFile(src, dest, operationID string, now time.Time) (BackupRecord, error) {
	data, err := os.ReadFile(src)
	if err != nil {
		return BackupRecord{}, fmt.Errorf("managedfile: back up %s: %w", src, err)
	}
	fi, err := os.Stat(src)
	if err != nil {
		return BackupRecord{}, fmt.Errorf("managedfile: stat %s: %w", src, err)
	}
	if err := WriteFileAtomic(dest, data, fi.Mode().Perm()); err != nil {
		return BackupRecord{}, err
	}
	return BackupRecord{
		Source:      src,
		Path:        dest,
		Digest:      Digest(data),
		Size:        int64(len(data)),
		Mode:        uint32(fi.Mode().Perm()),
		OperationID: operationID,
		Created:     now.UTC(),
	}, nil
}

// RestoreBackup writes a recorded backup back to dest, preserving the backup's
// recorded mode. Bytes are published atomically so a reader never sees a
// partial restoration.
func RestoreBackup(rec BackupRecord) error {
	data, err := os.ReadFile(rec.Path)
	if err != nil {
		return fmt.Errorf("managedfile: restore backup %s: %w", rec.Path, err)
	}
	if Digest(data) != rec.Digest {
		return fmt.Errorf("managedfile: backup %s changed after capture", rec.Path)
	}
	return WriteFileAtomic(rec.Source, data, os.FileMode(rec.Mode))
}

// Sidecar is the digest record published beside a managed resource. It lets a
// later operation prove what it published without re-rendering the resource.
type Sidecar struct {
	Path       string      `json:"path"`
	Kind       Kind        `json:"kind"`
	Digest     string      `json:"digest"`
	Generation string      `json:"generation,omitempty"`
	Entries    []TreeEntry `json:"entries,omitempty"`
}

// SidecarPath returns the sidecar path for a published resource: a sibling
// file, so a published directory stays exactly the generated bytes.
func SidecarPath(published string) string {
	return published + ".atomic-digest.json"
}

// WriteSidecar records a resource's digest beside it, durably.
func WriteSidecar(published string, sidecar Sidecar) error {
	sidecar.Path = published
	data, err := json.MarshalIndent(sidecar, "", "    ")
	if err != nil {
		return fmt.Errorf("managedfile: marshal sidecar for %s: %w", published, err)
	}
	data = append(data, '\n')
	if err := WriteFileAtomic(SidecarPath(published), data, 0o644); err != nil {
		return fmt.Errorf("managedfile: write sidecar for %s: %w", published, err)
	}
	return nil
}

// ReadSidecar reads the digest record published beside a resource.
func ReadSidecar(published string) (Sidecar, error) {
	data, err := os.ReadFile(SidecarPath(published))
	if err != nil {
		return Sidecar{}, fmt.Errorf("managedfile: read sidecar for %s: %w", published, err)
	}
	var sidecar Sidecar
	if err := json.Unmarshal(data, &sidecar); err != nil {
		return Sidecar{}, fmt.Errorf("managedfile: decode sidecar for %s: %w", published, err)
	}
	return sidecar, nil
}

// resourceDigest computes a resource's current digest for its kind.
func resourceDigest(path string, kind Kind) (string, error) {
	if kind == KindTree {
		digest, _, err := TreeDigest(path)
		return digest, err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("managedfile: digest %s: %w", path, err)
	}
	if kind == KindBlock {
		block, err := ManagedBlock(data)
		if err != nil {
			return "", fmt.Errorf("managedfile: digest block %s: %w", path, err)
		}
		return Digest(block), nil
	}
	return Digest(data), nil
}

// VerifySidecar recomputes the resource's digest and reports whether it still
// matches the published sidecar. A missing or unreadable sidecar is an error,
// not a false pass.
func VerifySidecar(published string) (bool, error) {
	sidecar, err := ReadSidecar(published)
	if err != nil {
		return false, err
	}
	kind := sidecar.Kind
	if kind == "" {
		kind = KindFile
	}
	digest, err := resourceDigest(published, kind)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	return digest == sidecar.Digest, nil
}
