package config

import (
	"fmt"
	"sort"
	"strings"
)

// Render produces a deterministic markdown snapshot of resolved config values.
// Keys are sorted. No timestamps. Byte-stable for same input.
// An empty Config still renders a file with the header so the @-ref resolves.
func Render(cfg *Config) string {
	m := Resolved(cfg)

	// Sort keys for determinism.
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Atomic resolved config\n")
	sb.WriteString("\n")
	sb.WriteString("<!-- Generated by `atomic config`. Do not edit by hand. -->\n")
	sb.WriteString("\n")

	// Group keys by section (first dotted component).
	// Schema v1 always has at least one key (output.signals.max_depth), so len(keys) > 0 here.
	type entry struct{ key, val string }
	sections := map[string][]entry{}
	var sectionOrder []string
	seen := map[string]bool{}
	for _, k := range keys {
		parts := strings.SplitN(k, ".", 2)
		sec := parts[0]
		if !seen[sec] {
			sectionOrder = append(sectionOrder, sec)
			seen[sec] = true
		}
		sections[sec] = append(sections[sec], entry{k, m[k]})
	}

	for _, sec := range sectionOrder {
		sb.WriteString(fmt.Sprintf("## [%s]\n\n", sec))
		for _, e := range sections[sec] {
			sb.WriteString(fmt.Sprintf("- `%s` = `%s`\n", e.key, e.val))
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

// Resolved returns a flat dotted-key → resolved-value map.
// Built-in defaults are filled in for any zero-value fields.
func Resolved(cfg *Config) map[string]string {
	// output.signals.max_depth: int zero-value (0) means "use default".
	// It also doubles as the zero-value-Config signal below.
	maxDepth := cfg.Output.Signals.MaxDepth
	zeroValueConfig := maxDepth <= 0
	if maxDepth <= 0 {
		maxDepth = signalsMaxDepthDefault
	}
	// For update.run_doctor: bool's zero value (false) is indistinguishable
	// from an explicit false without a sentinel. A literal zero-value Config
	// (e.g. &Config{}) has MaxDepth == 0; one produced by Default()/Load()
	// always has MaxDepth > 0 (absent → backfilled to the default, explicit
	// non-positive → rejected by Validate). So MaxDepth <= 0 means "zero-value
	// Config", in which case apply the run_doctor default too. A Default()/Load()
	// Config with RunDoctor == false is intentional and preserved.
	runDoctor := cfg.Update.RunDoctor
	if !runDoctor && zeroValueConfig {
		runDoctor = runDoctorDefault
	}
	return map[string]string{
		"output.signals.max_depth": fmt.Sprintf("%d", maxDepth),
		"update.run_doctor":        fmt.Sprintf("%t", runDoctor),
	}
}
