package config

import (
	"fmt"
	"sort"
	"strings"
)

// Render produces a deterministic markdown snapshot of resolved config values.
// Keys are sorted. No timestamps. Byte-stable for same input.
// An empty Config still renders a file with the header so the @-ref resolves.
func Render(cfg *Config) string {
	m := Resolved(cfg)

	// Sort keys for determinism.
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Atomic resolved config\n")
	sb.WriteString("\n")
	sb.WriteString("<!-- Generated by `atomic config`. Do not edit by hand. -->\n")
	sb.WriteString("\n")

	// Group keys by section (first dotted component).
	// Schema v1 always has at least one key (output.intensity), so len(keys) > 0 here.
	type entry struct{ key, val string }
	sections := map[string][]entry{}
	var sectionOrder []string
	seen := map[string]bool{}
	for _, k := range keys {
		parts := strings.SplitN(k, ".", 2)
		sec := parts[0]
		if !seen[sec] {
			sectionOrder = append(sectionOrder, sec)
			seen[sec] = true
		}
		sections[sec] = append(sections[sec], entry{k, m[k]})
	}

	for _, sec := range sectionOrder {
		sb.WriteString(fmt.Sprintf("## [%s]\n\n", sec))
		for _, e := range sections[sec] {
			sb.WriteString(fmt.Sprintf("- `%s` = `%s`\n", e.key, e.val))
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

// Resolved returns a flat dotted-key → resolved-value map.
// Built-in defaults are filled in for any zero-value fields.
func Resolved(cfg *Config) map[string]string {
	intensity := cfg.Output.Intensity
	if intensity == "" {
		intensity = intensityDefault
	}
	// For update.run_doctor: bool's zero value (false) is indistinguishable
	// from an explicit false without a sentinel. We use the same zero-value
	// signal as intensity: a Config where intensity == "" is a literal zero-value
	// struct, not one produced by Default() or Load(). In that case apply the
	// default for run_doctor too. A Config where intensity != "" was produced by
	// Default()/Load() — RunDoctor=false there is intentional and preserved.
	runDoctor := cfg.Update.RunDoctor
	if !runDoctor && intensity == intensityDefault && cfg.Output.Intensity == "" {
		// intensity was backfilled above (cfg.Output.Intensity was ""), meaning
		// this is a zero-value Config. Apply the run_doctor default too.
		runDoctor = runDoctorDefault
	}
	return map[string]string{
		"output.intensity":  intensity,
		"update.run_doctor": fmt.Sprintf("%t", runDoctor),
	}
}
