package wiki

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/damusix/atomic-claude/atomic/internal/rules"
)

// RefreshScope selects which wiki refresh pipeline produced a card set.
type RefreshScope string

const (
	// RefreshRepo is the repository-scope refresh: one pointer card per domain.
	RefreshRepo RefreshScope = "repo"
	// RefreshRealm is the realm-scope refresh: it spans multiple repository
	// bases, so it produces no scoped pointer rules.
	RefreshRealm RefreshScope = "realm"
)

// PointerCard is one repository-refresh domain pointer card. Domain fixes both
// the file name (rules/wiki/<domain>.md) and the wiki:<project-key>:<domain>
// record identity; Include is the card's paths: globs; Body is the
// pointer-index text the router supplied.
type PointerCard struct {
	Domain  string
	Include []string
	Body    string
}

// Refresh writes the canonical pointer cards for one wiki refresh and returns
// them as wiki-producer rule records. stateRoot is the selected
// repository-state directory (.claude by default), projectKey identifies the
// repository across worktrees.
//
// Repository scope writes one card per domain under <stateRoot>/rules/wiki/ and
// returns every card parsed through rules.ParseWiki. Cards are wholly
// pipeline-owned and regenerated every refresh, so a card whose domain is
// absent from this run's set is deleted. Realm scope spans multiple repository
// bases: it writes nothing and returns no records.
func Refresh(stateRoot, projectKey string, scope RefreshScope, cards []PointerCard) ([]rules.RuleRecord, error) {
	switch scope {
	case RefreshRealm:
		return nil, nil
	case RefreshRepo:
	default:
		return nil, fmt.Errorf("wiki: refresh: unknown scope %q", scope)
	}
	if stateRoot == "" {
		return nil, fmt.Errorf("wiki: refresh: empty state root")
	}
	if projectKey == "" {
		return nil, fmt.Errorf("wiki: refresh: empty project key")
	}

	ordered := make([]PointerCard, len(cards))
	copy(ordered, cards)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].Domain < ordered[j].Domain })

	rendered := make([][]byte, len(ordered))
	for i, card := range ordered {
		data, err := renderPointerCard(projectKey, card)
		if err != nil {
			return nil, err
		}
		rendered[i] = data
	}

	rulesRoot := filepath.Join(stateRoot, "rules")
	wikiDir := filepath.Join(rulesRoot, "wiki")

	if err := pruneCards(wikiDir, ordered); err != nil {
		return nil, err
	}

	for i, card := range ordered {
		if err := os.MkdirAll(wikiDir, 0o755); err != nil {
			return nil, fmt.Errorf("wiki: refresh: create %s: %w", wikiDir, err)
		}
		path := filepath.Join(wikiDir, card.Domain+".md")
		if err := writeFileAtomic(path, rendered[i]); err != nil {
			return nil, fmt.Errorf("wiki: refresh: write %s: %w", path, err)
		}
	}

	return rules.LoadWiki(rulesRoot, projectKey)
}

// pruneCards deletes every card whose domain is absent from cards, so a removed
// domain does not leave an owned projection behind.
func pruneCards(wikiDir string, cards []PointerCard) error {
	keep := make(map[string]bool, len(cards))
	for _, card := range cards {
		keep[card.Domain+".md"] = true
	}
	entries, err := os.ReadDir(wikiDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("wiki: refresh: read %s: %w", wikiDir, err)
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") || keep[entry.Name()] {
			continue
		}
		if err := os.Remove(filepath.Join(wikiDir, entry.Name())); err != nil {
			return fmt.Errorf("wiki: refresh: prune %s: %w", entry.Name(), err)
		}
	}
	return nil
}

// renderPointerCard renders one card's canonical bytes: frontmatter carrying
// only the paths: globs plus the pipeline-owned marker comment, then the body.
// rules.ParseWiki accepts no other frontmatter key, so a malformed card is
// refused here rather than written and discovered on the next load.
func renderPointerCard(projectKey string, card PointerCard) ([]byte, error) {
	if card.Domain == "" {
		return nil, fmt.Errorf("wiki: refresh: card has no domain")
	}
	source := "rules/wiki/" + card.Domain + ".md"
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("# generated by /refresh-wiki — do not hand-edit; regenerated every refresh\n")
	b.WriteString("paths:\n")
	for _, glob := range card.Include {
		fmt.Fprintf(&b, "  - %q\n", glob)
	}
	b.WriteString("---\n\n")
	b.WriteString(card.Body)
	data := []byte(b.String())
	if _, err := rules.ParseWiki(projectKey, source, data); err != nil {
		return nil, fmt.Errorf("wiki: refresh: %w", err)
	}
	return data, nil
}
