// Code generated by cmd/bundle-mirror. DO NOT EDIT.
package embedded

// Artifact describes one file in the embedded artifact bundle.
type Artifact struct {
	Kind   string // "agent" | "command" | "skill" | "output-style" | "rule" | "claude-md"
	Source string // path inside the embedded FS, e.g. "bundle/agents/atomic-builder.md"
	Target string // path inside the target dir, e.g. "agents/atomic-builder.md"
	SHA256 string // hex-encoded SHA256 of the embedded source bytes
}

// Manifest returns the explicit allowlist of bundled artifacts.
// Generated at build time by cmd/bundle-mirror; commit the result.
func Manifest() []Artifact {
	return []Artifact{
		{Kind: "agent", Source: "bundle/agents/atomic-implementer.md", Target: "agents/atomic-implementer.md", SHA256: "cf0f0d2110557e88146b71f79df20f92663cdb999b87b8458535abe97f1af150"},
		{Kind: "agent", Source: "bundle/agents/atomic-investigator.md", Target: "agents/atomic-investigator.md", SHA256: "a8859aa135804d59aa0665a856e1f1a24d085be30e3f251a562944586c019b58"},
		{Kind: "agent", Source: "bundle/agents/atomic-reviewer.md", Target: "agents/atomic-reviewer.md", SHA256: "f0246443dc15fce656c44a61d0f2f16a96e37727b922e9010f0e7a14ef0e55f5"},
		{Kind: "agent", Source: "bundle/agents/atomic-strategist.md", Target: "agents/atomic-strategist.md", SHA256: "2d002229a7a7ae6f865c550c7aa941f9a01e8572e3610379d12ff5fe015bf162"},
		{Kind: "agent", Source: "bundle/agents/atomic-wiki-inferrer.md", Target: "agents/atomic-wiki-inferrer.md", SHA256: "a9416ba3997933204b7607cf5c8758c7c5005930183dc6bedd7264310f5f9a5a"},
		{Kind: "claude-md", Source: "bundle/CLAUDE.md", Target: "CLAUDE.md", SHA256: "10a54951b78a9fc4574e7d8be950cbc2faa245a2342a7e1b3bf67560eccf96b0"},
		{Kind: "command", Source: "bundle/commands/_templates/implementer-prompt.md", Target: "commands/_templates/implementer-prompt.md", SHA256: "88821c30f61b773218b90332f2060eec09979515545aaddfcb10081f1e8ce14f"},
		{Kind: "command", Source: "bundle/commands/_templates/reviewer-prompt.md", Target: "commands/_templates/reviewer-prompt.md", SHA256: "296889105ed096f4afb9239c5931f9b900037d55e676f89bf3023daf5d62ffed"},
		{Kind: "command", Source: "bundle/commands/atomic-help.md", Target: "commands/atomic-help.md", SHA256: "728dc25e2d1ecf952881083eb70cbb7a7c733d9aa0bab543eb4adf500e110273"},
		{Kind: "command", Source: "bundle/commands/atomic-improve.md", Target: "commands/atomic-improve.md", SHA256: "8bd4c5ba0b1002285544898ae5ca65284e744ae7a8c60e379239c76f08b75121"},
		{Kind: "command", Source: "bundle/commands/atomic-plan.md", Target: "commands/atomic-plan.md", SHA256: "b17abc056040a1af467b34839d8dc7441629b6b67982480a23aa832e45c79705"},
		{Kind: "command", Source: "bundle/commands/atomic-setup.md", Target: "commands/atomic-setup.md", SHA256: "ed7ebe2c90da7829f8a04277daef575742022bf4cd3bbd9b3b10f1afe1fd9290"},
		{Kind: "command", Source: "bundle/commands/autopilot.md", Target: "commands/autopilot.md", SHA256: "49b39302316f9ff4d0b2a5b95b6368fb2821b7f53cb77de5a177176008710895"},
		{Kind: "command", Source: "bundle/commands/commit.md", Target: "commands/commit.md", SHA256: "199dd9f35badae7d6c19a8b7c89676f9e90536a6b1d34f21586c6ae7c687a719"},
		{Kind: "command", Source: "bundle/commands/documentation.md", Target: "commands/documentation.md", SHA256: "abf14f993cac9a8811acabb092f228d1021420683cd2f3ba1a40a62516a70826"},
		{Kind: "command", Source: "bundle/commands/follow-up.md", Target: "commands/follow-up.md", SHA256: "a79e6a609297aa83d782da5ca7f1338f3d95b0ce0ee74f540889fc6f2f5b2490"},
		{Kind: "command", Source: "bundle/commands/gather-evidence.md", Target: "commands/gather-evidence.md", SHA256: "54f065885e732c9ffbcfdb80f8588b68174185e34704e6b6b39ac53d73bb030b"},
		{Kind: "command", Source: "bundle/commands/git-cleanup.md", Target: "commands/git-cleanup.md", SHA256: "848d8ab8cfb605182036671d7e5e66a70bf06663f6568232a912c35558e8f35d"},
		{Kind: "command", Source: "bundle/commands/pressure-test.md", Target: "commands/pressure-test.md", SHA256: "b4d7fcffd11b7b2dab7e6d0e3db285164f272d507e169b48d284d4347f4d6d10"},
		{Kind: "command", Source: "bundle/commands/refresh-wiki.md", Target: "commands/refresh-wiki.md", SHA256: "cc098b77560026e8daad794b152b54857177efe902eeb33784cd94326867e26a"},
		{Kind: "command", Source: "bundle/commands/remind-me.md", Target: "commands/remind-me.md", SHA256: "41433cbfc8b4d139d133885c4d6caacfb99c395767824dae60203baad950366f"},
		{Kind: "command", Source: "bundle/commands/report-issue-with-atomic.md", Target: "commands/report-issue-with-atomic.md", SHA256: "b68d3a8f1c5464e7a6154b657faf69450edf0f00feba23ca93e0106dcf13bafa"},
		{Kind: "command", Source: "bundle/commands/report-issue.md", Target: "commands/report-issue.md", SHA256: "6bb11804c2444a987d515cbadfdf139f11b2c46d6ef73bd875dcad35f3d859f0"},
		{Kind: "command", Source: "bundle/commands/review-branch.md", Target: "commands/review-branch.md", SHA256: "218d3daa3ae11ec2134a8f5ff0cf93901b30c5069aeb1750dcf12ce54c0238d4"},
		{Kind: "command", Source: "bundle/commands/session-report.md", Target: "commands/session-report.md", SHA256: "226b56ed1163395441fac8732bd5131a2f7cb906aa31c782dbd6718cd21e978d"},
		{Kind: "command", Source: "bundle/commands/subagent-diagnose.md", Target: "commands/subagent-diagnose.md", SHA256: "88a953626b52f073fd35efef86586173273af84dcd61e27843af9188f5691261"},
		{Kind: "command", Source: "bundle/commands/subagent-implementation.md", Target: "commands/subagent-implementation.md", SHA256: "16013e9d95ecc3e7f73f2d4ca446a456f754a4db48629ba4f7ce9590422b5e19"},
		{Kind: "command", Source: "bundle/commands/undo-commit.md", Target: "commands/undo-commit.md", SHA256: "1fc57693e90c05a16866599703718863ecb7dbe31754ef210dbd2b73c487ea81"},
		{Kind: "command", Source: "bundle/commands/watch-ci.md", Target: "commands/watch-ci.md", SHA256: "4097862c18d8f7ca68dddf01c45ca67bffac11529c086e188fa77d9109b82700"},
		{Kind: "output-style", Source: "bundle/output-styles/atomic.md", Target: "output-styles/atomic.md", SHA256: "e19760d5d351713bd02ffae40d2253488922ef6ad3f725c4ad0a4961b5e26135"},
		{Kind: "rule", Source: "bundle/rules/python/style.md", Target: "rules/python/style.md", SHA256: "79b5bc1f7b33e4f065e9645193eb6b3cb8227babb92c7e62ced0164673b0546b"},
		{Kind: "rule", Source: "bundle/rules/specs/spec-currency.md", Target: "rules/specs/spec-currency.md", SHA256: "c7e2c88d68665bb056192e74c842ee25f44e4bd1ede5729d63a24f37183901ca"},
		{Kind: "rule", Source: "bundle/rules/typescript/style.md", Target: "rules/typescript/style.md", SHA256: "a520e9df348e06c5f0772d268a16ef03ea6fd2f77d6a2a192bf566b91db186d7"},
		{Kind: "skill", Source: "bundle/skills/atomic-commit/SKILL.md", Target: "skills/atomic-commit/SKILL.md", SHA256: "b6d6bd699dc92301c28ffb3a673827d7be9c5207c607fe3e3fdeac0513b49420"},
		{Kind: "skill", Source: "bundle/skills/atomic-debug/SKILL.md", Target: "skills/atomic-debug/SKILL.md", SHA256: "becc4cd2545a1a2755f08cf4da5135d4b7b930484137696476cba5805fded3c8"},
		{Kind: "skill", Source: "bundle/skills/atomic-documentation/SKILL.md", Target: "skills/atomic-documentation/SKILL.md", SHA256: "4216e7ab96aef655dbdd2a8bc0a5f8ce7e2da0dc4c922b0a4846b1e02b1ec4a0"},
		{Kind: "skill", Source: "bundle/skills/atomic-prose/SKILL.md", Target: "skills/atomic-prose/SKILL.md", SHA256: "fe2cbad6c7e239949c67a3f1b681da94f6ee26e713d5b9d0572a7d5a98201d88"},
		{Kind: "skill", Source: "bundle/skills/atomic-review/SKILL.md", Target: "skills/atomic-review/SKILL.md", SHA256: "5eab2efd6364adaa7b5d64687af819ffc658bf2295ec7e95739351bf7e4c3851"},
		{Kind: "skill", Source: "bundle/skills/atomic-tdd/SKILL.md", Target: "skills/atomic-tdd/SKILL.md", SHA256: "8b5d6c0ef995a07d1b34f9fcee7647c446781e096894acb6713f53c610b452de"},
		{Kind: "skill", Source: "bundle/skills/atomic-verify/SKILL.md", Target: "skills/atomic-verify/SKILL.md", SHA256: "5668ada68772f2ec43129305d51694d7b93deaa8577653ac7fc7b5bfcb2144e1"},
		{Kind: "skill", Source: "bundle/skills/atomic-visual-options/SKILL.md", Target: "skills/atomic-visual-options/SKILL.md", SHA256: "c33181fb08ef20597c15b480cb932eda7a5aebded1962ce098935805b28ee19e"},
		{Kind: "skill", Source: "bundle/skills/atomic-wiki/SKILL.md", Target: "skills/atomic-wiki/SKILL.md", SHA256: "bca3dfd771275d71d99f4e1303481263d57e2021c06eccd66fe61b323797a30d"},
		{Kind: "skill", Source: "bundle/skills/atomic-wiki/references/realm.md", Target: "skills/atomic-wiki/references/realm.md", SHA256: "0ca780067af3c3ba0988b4da2c141f99683e175ef23baefd99c9948185eaba55"},
		{Kind: "skill", Source: "bundle/skills/atomic-wiki/references/repo.md", Target: "skills/atomic-wiki/references/repo.md", SHA256: "3614c4390cf8ab2b3a81b6242f2d69f37fb6a5b45cc495d844920f4b5fe95499"},
	}
}
