// Code generated by cmd/bundle-mirror. DO NOT EDIT.
package embedded

// Artifact describes one file in the embedded artifact bundle.
type Artifact struct {
	Kind   string // "agent" | "command" | "skill" | "output-style" | "rule" | "claude-md"
	Source string // path inside the embedded FS, e.g. "bundle/agents/atomic-builder.md"
	Target string // path inside the target dir, e.g. "agents/atomic-builder.md"
	SHA256 string // hex-encoded SHA256 of the embedded source bytes
}

// Manifest returns the explicit allowlist of bundled artifacts.
// Generated at build time by cmd/bundle-mirror; commit the result.
func Manifest() []Artifact {
	return []Artifact{
		{Kind: "agent", Source: "bundle/agents/atomic-builder.md", Target: "agents/atomic-builder.md", SHA256: "de0760c9a38f299bc88ed4e113caba67160f24a38f15a83a09261f8c755b3689"},
		{Kind: "agent", Source: "bundle/agents/atomic-claude-merger.md", Target: "agents/atomic-claude-merger.md", SHA256: "3d6572da7e0598276b51a65a4ab09b60614b1775a34b2d8bba6f1b041f17a038"},
		{Kind: "agent", Source: "bundle/agents/atomic-git-scout.md", Target: "agents/atomic-git-scout.md", SHA256: "e6c2290933f09ea21e838265b04491f0376bbbab619f76f5bd1368421bf0f31b"},
		{Kind: "agent", Source: "bundle/agents/atomic-haiku.md", Target: "agents/atomic-haiku.md", SHA256: "37502960fa8cfd953f3d6d6308339b795771b3d5e58fa76da5f2c0e92fdb17cc"},
		{Kind: "agent", Source: "bundle/agents/atomic-investigator.md", Target: "agents/atomic-investigator.md", SHA256: "cbcc64fed0e96526106e37897d6f5c2f000859f1c808d0d173c1160c1fbe375b"},
		{Kind: "agent", Source: "bundle/agents/atomic-reviewer.md", Target: "agents/atomic-reviewer.md", SHA256: "79e762bfc557e141158840456fcdc3f7a9fa3a8a080c2c04426221606d2fc881"},
		{Kind: "agent", Source: "bundle/agents/atomic-signals-inferrer.md", Target: "agents/atomic-signals-inferrer.md", SHA256: "6b59ad7aa699324cffff462ccfa72ba701a666da40a6bfc487c0f50d389f01ee"},
		{Kind: "agent", Source: "bundle/agents/atomic-strategist.md", Target: "agents/atomic-strategist.md", SHA256: "4d7aac1e2d195a292e97e2c9bb2ee7c6c2ea243cef68947e465cb13f965535c3"},
		{Kind: "agent", Source: "bundle/agents/atomic-surgeon.md", Target: "agents/atomic-surgeon.md", SHA256: "b0de95844adb12433be6fb232d4779cd98badef7a08c7af2020c25f31323dad1"},
		{Kind: "claude-md", Source: "bundle/CLAUDE.md", Target: "CLAUDE.md", SHA256: "2b96ffbc011f25a30c9c701729ca5eea9c4436b61a9221ffdacd71b49fc501a1"},
		{Kind: "command", Source: "bundle/commands/_templates/implementer-prompt.md", Target: "commands/_templates/implementer-prompt.md", SHA256: "88821c30f61b773218b90332f2060eec09979515545aaddfcb10081f1e8ce14f"},
		{Kind: "command", Source: "bundle/commands/_templates/reviewer-prompt.md", Target: "commands/_templates/reviewer-prompt.md", SHA256: "296889105ed096f4afb9239c5931f9b900037d55e676f89bf3023daf5d62ffed"},
		{Kind: "command", Source: "bundle/commands/atomic-claude-merge.md", Target: "commands/atomic-claude-merge.md", SHA256: "0ad7fdefc2f579471f0811fa4bdfde7b2a3a16cad42a33dcf547f39bace9bd02"},
		{Kind: "command", Source: "bundle/commands/atomic-help.md", Target: "commands/atomic-help.md", SHA256: "998eafe0ee59d321e24343170b900e25a1b5bef7e798bd49b1dcd189a85fa49b"},
		{Kind: "command", Source: "bundle/commands/atomic-improve.md", Target: "commands/atomic-improve.md", SHA256: "e1392d14ba40c34f4806b3dd268bf793c94b6d60076b5a22510f841cc9f3b56b"},
		{Kind: "command", Source: "bundle/commands/atomic-plan.md", Target: "commands/atomic-plan.md", SHA256: "1f12f8d15d9498b51b1faf6a0123263d9db157a09415b4e59e6b86b8c65732f4"},
		{Kind: "command", Source: "bundle/commands/atomic-setup.md", Target: "commands/atomic-setup.md", SHA256: "e71434a4815ef944df9fbe04f8cf9e99d818b0282139c3a6f1894e089705db82"},
		{Kind: "command", Source: "bundle/commands/autopilot.md", Target: "commands/autopilot.md", SHA256: "0f92fb2c0b65f8345be61ccae16cb7e327684267b0c01f5e6fb7ddc5eaeea963"},
		{Kind: "command", Source: "bundle/commands/commit-and-merge.md", Target: "commands/commit-and-merge.md", SHA256: "7cce470a76140dcbc0ad7885ae4385e4ec2b8c2c0f2f8c9356c5f67b02eb2f09"},
		{Kind: "command", Source: "bundle/commands/commit-and-pr.md", Target: "commands/commit-and-pr.md", SHA256: "7f97d58b47098d5687111bb11af33dd62d2a6bd8c8ebb524048987d109e88d53"},
		{Kind: "command", Source: "bundle/commands/commit-and-push.md", Target: "commands/commit-and-push.md", SHA256: "b276d4a0a244ecb1e6e1dfad06fb7f7f24a9f236a281ae4180954b23b41efec2"},
		{Kind: "command", Source: "bundle/commands/commit-and-squash.md", Target: "commands/commit-and-squash.md", SHA256: "2eb0b0bf9e8b6d7623faef16e1f8a0da64cbc202164310de822b7958575a85cc"},
		{Kind: "command", Source: "bundle/commands/commit-only.md", Target: "commands/commit-only.md", SHA256: "182526944a4c990b931460c909a10d55ee4972efd2bffb8c7ece1adf47d343f4"},
		{Kind: "command", Source: "bundle/commands/documentation.md", Target: "commands/documentation.md", SHA256: "9c9db0b65ff87cdda05f7a58c5dee2967b5a15d12acba36d2b7b37e229afa263"},
		{Kind: "command", Source: "bundle/commands/follow-up.md", Target: "commands/follow-up.md", SHA256: "a79e6a609297aa83d782da5ca7f1338f3d95b0ce0ee74f540889fc6f2f5b2490"},
		{Kind: "command", Source: "bundle/commands/gather-evidence.md", Target: "commands/gather-evidence.md", SHA256: "54f065885e732c9ffbcfdb80f8588b68174185e34704e6b6b39ac53d73bb030b"},
		{Kind: "command", Source: "bundle/commands/git-cleanup.md", Target: "commands/git-cleanup.md", SHA256: "5724c556392b5d760230f00d49d0e3d656aa116a75e0402980dd44e7e450324c"},
		{Kind: "command", Source: "bundle/commands/merge-to-main.md", Target: "commands/merge-to-main.md", SHA256: "9491e899b782c4e2eceb501c3a4669b12b98e406fda0f485e09b231193d23f77"},
		{Kind: "command", Source: "bundle/commands/pr-only.md", Target: "commands/pr-only.md", SHA256: "1c5e6b1df94c793449fecaf2624bf606b111f3ea4f20d89a4cfba0c289187a26"},
		{Kind: "command", Source: "bundle/commands/pressure-test.md", Target: "commands/pressure-test.md", SHA256: "b4d7fcffd11b7b2dab7e6d0e3db285164f272d507e169b48d284d4347f4d6d10"},
		{Kind: "command", Source: "bundle/commands/push-only.md", Target: "commands/push-only.md", SHA256: "52795549ab92025214908d3e2c2a57183d0205ab98b77ab35568af38fd6bd4ed"},
		{Kind: "command", Source: "bundle/commands/refresh-signals.md", Target: "commands/refresh-signals.md", SHA256: "a43b86b319485d4cf70ab38b81ef27b38cea39a0954bbc6d65846e7ca94c2005"},
		{Kind: "command", Source: "bundle/commands/refresh-wiki.md", Target: "commands/refresh-wiki.md", SHA256: "5b308667f65cb176e1f03412e7d6e026383f52df31e03699aaab63553ae96c7c"},
		{Kind: "command", Source: "bundle/commands/remind-me.md", Target: "commands/remind-me.md", SHA256: "41433cbfc8b4d139d133885c4d6caacfb99c395767824dae60203baad950366f"},
		{Kind: "command", Source: "bundle/commands/report-issue-with-atomic.md", Target: "commands/report-issue-with-atomic.md", SHA256: "423d6fad23e75dfb061cb46134640e1f54adf7571773400fbbd43e897dbeabb4"},
		{Kind: "command", Source: "bundle/commands/report-issue.md", Target: "commands/report-issue.md", SHA256: "6bb11804c2444a987d515cbadfdf139f11b2c46d6ef73bd875dcad35f3d859f0"},
		{Kind: "command", Source: "bundle/commands/review-branch.md", Target: "commands/review-branch.md", SHA256: "d560b3d9787c64df3f7ff1f1a22ffe497ba15cc5c01296e2fa81d882e987b367"},
		{Kind: "command", Source: "bundle/commands/session-report.md", Target: "commands/session-report.md", SHA256: "3dd34bdd610db5db483a2cdd30bcfd1efb54ed38e30860a836a01326a673b36c"},
		{Kind: "command", Source: "bundle/commands/squash-and-merge.md", Target: "commands/squash-and-merge.md", SHA256: "42636abf29204e92cb6264170bded3bd67bdd52ef3412ae18d0d949bd86792f9"},
		{Kind: "command", Source: "bundle/commands/squash-only.md", Target: "commands/squash-only.md", SHA256: "cd8cd086962b1128c5dd34bfb132e4e7b7144385cc605205c409f3b3f565ee9b"},
		{Kind: "command", Source: "bundle/commands/subagent-diagnose.md", Target: "commands/subagent-diagnose.md", SHA256: "97c1bddac31ba0034f693f9799f8c1923c3626f6f36ef4f7d9c69798b34f04bb"},
		{Kind: "command", Source: "bundle/commands/subagent-implementation.md", Target: "commands/subagent-implementation.md", SHA256: "0ca84f277a1d2d47b783b76b6787f90a930ae4b96bc86ad37a3c863c3a86d74b"},
		{Kind: "command", Source: "bundle/commands/undo-commit.md", Target: "commands/undo-commit.md", SHA256: "7def686f1a31f3b90fdd537806e2953cc6f1d85abca630eb97089aaf148655f7"},
		{Kind: "command", Source: "bundle/commands/watch-ci.md", Target: "commands/watch-ci.md", SHA256: "5039f000385227026cdc52e85a4863b8bc064e79d8681e65e6520a5ab71a66fa"},
		{Kind: "command", Source: "bundle/commands/worktree-start.md", Target: "commands/worktree-start.md", SHA256: "6a5d800f4696c73572ffac6e198d100ed4885f7d6cd0bf664f307f8896eb2aa9"},
		{Kind: "output-style", Source: "bundle/output-styles/atomic.md", Target: "output-styles/atomic.md", SHA256: "05ced557ed8a0295eaadac9a40bd6bebaa2a5865f5539657b680c91a0645b82b"},
		{Kind: "rule", Source: "bundle/rules/python/style.md", Target: "rules/python/style.md", SHA256: "79b5bc1f7b33e4f065e9645193eb6b3cb8227babb92c7e62ced0164673b0546b"},
		{Kind: "rule", Source: "bundle/rules/specs/spec-currency.md", Target: "rules/specs/spec-currency.md", SHA256: "e1ef7ae92fee6d19c161cced0218cbfb5391a6dd2bd1a6f19d5b0c3facdedd2f"},
		{Kind: "rule", Source: "bundle/rules/typescript/style.md", Target: "rules/typescript/style.md", SHA256: "a520e9df348e06c5f0772d268a16ef03ea6fd2f77d6a2a192bf566b91db186d7"},
		{Kind: "skill", Source: "bundle/skills/atomic-commit/SKILL.md", Target: "skills/atomic-commit/SKILL.md", SHA256: "2d3e552a4864c4d173146d01e34bca11834b48a049fcc180e407f00e7ee05349"},
		{Kind: "skill", Source: "bundle/skills/atomic-debug/SKILL.md", Target: "skills/atomic-debug/SKILL.md", SHA256: "07ff7c25646a9d27b7900f2e0f6a8f552f9b4ac6da566dd32858e42c96edb896"},
		{Kind: "skill", Source: "bundle/skills/atomic-documentation/SKILL.md", Target: "skills/atomic-documentation/SKILL.md", SHA256: "4216e7ab96aef655dbdd2a8bc0a5f8ce7e2da0dc4c922b0a4846b1e02b1ec4a0"},
		{Kind: "skill", Source: "bundle/skills/atomic-prose/SKILL.md", Target: "skills/atomic-prose/SKILL.md", SHA256: "fe2cbad6c7e239949c67a3f1b681da94f6ee26e713d5b9d0572a7d5a98201d88"},
		{Kind: "skill", Source: "bundle/skills/atomic-review/SKILL.md", Target: "skills/atomic-review/SKILL.md", SHA256: "12479e32c4f5df7f546391e3933d4dc86f281dbfdabda9cd8edf91deeb28eb11"},
		{Kind: "skill", Source: "bundle/skills/atomic-tdd/SKILL.md", Target: "skills/atomic-tdd/SKILL.md", SHA256: "627b43f286e2c11e51c63eac3dbe337a60abc341c56ed608de5478fc83e1feb7"},
		{Kind: "skill", Source: "bundle/skills/atomic-verify/SKILL.md", Target: "skills/atomic-verify/SKILL.md", SHA256: "5668ada68772f2ec43129305d51694d7b93deaa8577653ac7fc7b5bfcb2144e1"},
	}
}
