// Code generated by cmd/bundle-mirror. DO NOT EDIT.
package embedded

// Artifact describes one file in the embedded artifact bundle.
type Artifact struct {
	Kind   string // "agent" | "command" | "skill" | "output-style" | "rule" | "claude-md"
	Source string // path inside the embedded FS, e.g. "bundle/agents/atomic-builder.md"
	Target string // path inside the target dir, e.g. "agents/atomic-builder.md"
	SHA256 string // hex-encoded SHA256 of the embedded source bytes
}

// Manifest returns the explicit allowlist of bundled artifacts.
// Generated at build time by cmd/bundle-mirror; commit the result.
func Manifest() []Artifact {
	return []Artifact{
		{Kind: "agent", Source: "bundle/agents/atomic-builder.md", Target: "agents/atomic-builder.md", SHA256: "fd8b84f23d2aca51ae9574f2b6ba5d7759e87b0ae3d4f1240b43c89c37a43645"},
		{Kind: "agent", Source: "bundle/agents/atomic-claude-merger.md", Target: "agents/atomic-claude-merger.md", SHA256: "1320ab39bb84942d3bc8b957587ab4cf7954feb9dabcf0fe67bca597bf8507cc"},
		{Kind: "agent", Source: "bundle/agents/atomic-git-scout.md", Target: "agents/atomic-git-scout.md", SHA256: "e9bebd783ca11776971acd7667ba225fdc1f894d74c50574222960882c9f7be8"},
		{Kind: "agent", Source: "bundle/agents/atomic-haiku.md", Target: "agents/atomic-haiku.md", SHA256: "76808781257409dd31fe6cdf79d27f338459a57e3ec7a94b6b997d332ef1b201"},
		{Kind: "agent", Source: "bundle/agents/atomic-investigator.md", Target: "agents/atomic-investigator.md", SHA256: "ab568719360d0076ab6773cefef4982cd395e136cc818beae07bd74a31ce72bd"},
		{Kind: "agent", Source: "bundle/agents/atomic-reviewer.md", Target: "agents/atomic-reviewer.md", SHA256: "2cf4529b07a4b7313278daace312ac0f05e228633fcfe333ced64f59bf014093"},
		{Kind: "agent", Source: "bundle/agents/atomic-signals-inferrer.md", Target: "agents/atomic-signals-inferrer.md", SHA256: "09a83f235d5080efc954066986c77f6daaf78a49993a29e75c4a31e8b5214f07"},
		{Kind: "agent", Source: "bundle/agents/atomic-strategist.md", Target: "agents/atomic-strategist.md", SHA256: "6a8433f9c1a6dd871f9fbce41be94862adebcaedb1dffb96c3d50bcbd2bfb68a"},
		{Kind: "agent", Source: "bundle/agents/atomic-surgeon.md", Target: "agents/atomic-surgeon.md", SHA256: "abe9b60dc48e9edcdc1dd17a4b1da2edda09a1b00304b0fb81172cb6b8c169d6"},
		{Kind: "claude-md", Source: "bundle/CLAUDE.md", Target: "CLAUDE.md", SHA256: "23f987402aadb05340b42ac2eb1ee3c4d043d8bfa62d07918158e8239214ef6d"},
		{Kind: "command", Source: "bundle/commands/atomic-claude-merge.md", Target: "commands/atomic-claude-merge.md", SHA256: "38c153e4abc60ae008e16dab507c9b0743e2a31c800d3d70110548e92ab6f3cd"},
		{Kind: "command", Source: "bundle/commands/atomic-compress.md", Target: "commands/atomic-compress.md", SHA256: "77b0dec348cbb7dafa08ff2860faa7e23c2809f6b978096f2ebc3fe8cf907735"},
		{Kind: "command", Source: "bundle/commands/atomic-plan.md", Target: "commands/atomic-plan.md", SHA256: "18dae12bd1255c1b64c9159a96d41ae7cac1096de8a78a9577a5d705dd3fe956"},
		{Kind: "command", Source: "bundle/commands/atomic-setup.md", Target: "commands/atomic-setup.md", SHA256: "de93272657b793cc8c0e4eb0ac51ddcf8402523851640fc94a0a3fb49539c997"},
		{Kind: "command", Source: "bundle/commands/commit-and-merge.md", Target: "commands/commit-and-merge.md", SHA256: "fc6f143f42f517aee5fd0a5a15cd5748a115debf7df05cb2808461ad0535c2d4"},
		{Kind: "command", Source: "bundle/commands/commit-and-pr.md", Target: "commands/commit-and-pr.md", SHA256: "b547a8a0896999825b628917e3a05f4032ba22f905260cba9ab8480e7c1b3419"},
		{Kind: "command", Source: "bundle/commands/commit-and-push.md", Target: "commands/commit-and-push.md", SHA256: "f105826013e68788cc2fce1c11531d82415c161dc2bf1ccda89f7688fdbab078"},
		{Kind: "command", Source: "bundle/commands/commit-and-squash.md", Target: "commands/commit-and-squash.md", SHA256: "b72613c83da50dde750807b146213b8418b001ab11e90eede72c12b4e0101659"},
		{Kind: "command", Source: "bundle/commands/commit-only.md", Target: "commands/commit-only.md", SHA256: "a17df90e0defff2a470ca53f5724891528b702104eff9951c54533826a383e61"},
		{Kind: "command", Source: "bundle/commands/documentation.md", Target: "commands/documentation.md", SHA256: "61c2bf21423e68830fb977e1b685aed06bcb4b1dac719859fdcc0f883f30e258"},
		{Kind: "command", Source: "bundle/commands/follow-up.md", Target: "commands/follow-up.md", SHA256: "a28b07c64a773a1a227ab914bcadf7fc96983b07c232874d066ece3f7f9135ce"},
		{Kind: "command", Source: "bundle/commands/git-cleanup.md", Target: "commands/git-cleanup.md", SHA256: "039f8937885b8ad4bb7f1012c4714f0552f94c6f87b7dcb38a243ab94e7d1d9f"},
		{Kind: "command", Source: "bundle/commands/initialize-signals.md", Target: "commands/initialize-signals.md", SHA256: "8bf2d149a3a964e7ffd674d1ca3c669f0f12b36ac475e1d5bde64aa8bf100721"},
		{Kind: "command", Source: "bundle/commands/merge-to-main.md", Target: "commands/merge-to-main.md", SHA256: "5357b3d1e7bad5ce5c61af39d0bcd1be44d858d99f411e62248f029cdf667e2f"},
		{Kind: "command", Source: "bundle/commands/pr-only.md", Target: "commands/pr-only.md", SHA256: "090d174c1fdd93ff6fabbbbb01cfac0f94ee3e2a33387cdce943ace632665031"},
		{Kind: "command", Source: "bundle/commands/pressure-test.md", Target: "commands/pressure-test.md", SHA256: "f40d620e1b447198fec905ba3343b0a4e6b666d19a493527910689a17b2d8c8b"},
		{Kind: "command", Source: "bundle/commands/push-only.md", Target: "commands/push-only.md", SHA256: "a4d8a8a7e209416a0c6c1e53ef52b71bfa2646d1c9e496987ae45474e0592dda"},
		{Kind: "command", Source: "bundle/commands/refresh-signals.md", Target: "commands/refresh-signals.md", SHA256: "87afb96672e1ba4271d6f3aaa8d9f0989670a0a0a434e24983b949bd4a82233a"},
		{Kind: "command", Source: "bundle/commands/remind-me.md", Target: "commands/remind-me.md", SHA256: "d825df1dca502caac1fb7405b81c1567510573954d0fec47fab3205a6ce5596f"},
		{Kind: "command", Source: "bundle/commands/report-issue-with-atomic.md", Target: "commands/report-issue-with-atomic.md", SHA256: "71e45426ea940911bd804125fcb127cd8b15204304091cc0bc830156b59ebd89"},
		{Kind: "command", Source: "bundle/commands/report-issue.md", Target: "commands/report-issue.md", SHA256: "f80dd239e23f3d7a02bc90aa7af990420f4d616239c7f25dc6c9bfb826354de3"},
		{Kind: "command", Source: "bundle/commands/review-branch.md", Target: "commands/review-branch.md", SHA256: "7baebd545a71e9d4920bc9412f3e18a983e05cd801009121118775947153a52a"},
		{Kind: "command", Source: "bundle/commands/session-report.md", Target: "commands/session-report.md", SHA256: "5ea0799831b7fccb2d0786b41677e9120b355796e5bdd7e03118d0a5b1e317f5"},
		{Kind: "command", Source: "bundle/commands/squash-and-merge.md", Target: "commands/squash-and-merge.md", SHA256: "22dba02d2b3d0eb1c38419bf40ea115babc84b9babaa784a79c88445e521fb76"},
		{Kind: "command", Source: "bundle/commands/squash-only.md", Target: "commands/squash-only.md", SHA256: "9f65f0370b2ae2a3462b2b7e18a8e5fd6f19c824ed5a40de2131ae4b4ddbb8e6"},
		{Kind: "command", Source: "bundle/commands/subagent-diagnose.md", Target: "commands/subagent-diagnose.md", SHA256: "617ab7805dd80b0ff1e799c4f40399f6c2daec1697d0ef2bf2ed7f871435a9cc"},
		{Kind: "command", Source: "bundle/commands/subagent-implementation.md", Target: "commands/subagent-implementation.md", SHA256: "5edf631c69b2b2f82fb49bd8bc59448e6a4cac6c5095ceeda47d7de49dabbaf7"},
		{Kind: "command", Source: "bundle/commands/undo-commit.md", Target: "commands/undo-commit.md", SHA256: "db504e15a10aab4648159268ea67450208ce4733d3bd7df57398b2ff9722c57b"},
		{Kind: "command", Source: "bundle/commands/watch-ci.md", Target: "commands/watch-ci.md", SHA256: "464a3dea1a496bf9aa48cb94064d725c3dc41e00ce1fa0518fc7f39149d535ff"},
		{Kind: "command", Source: "bundle/commands/worktree-start.md", Target: "commands/worktree-start.md", SHA256: "e3736fb4f8fd4b305e3849705ef79f1ab902f00631640d9f00099cc60b4bb610"},
		{Kind: "output-style", Source: "bundle/output-styles/atomic.md", Target: "output-styles/atomic.md", SHA256: "27f21698e58b5c48f25992f14d3a6b6973ecca6d2eaceebc272d2385998142d5"},
		{Kind: "rule", Source: "bundle/rules/python/style.md", Target: "rules/python/style.md", SHA256: "f1a8b083bc6b7ed6567e12758852d96aff48efdd6e6414d8ca6086a723228f36"},
		{Kind: "rule", Source: "bundle/rules/typescript/style.md", Target: "rules/typescript/style.md", SHA256: "90e60e16dc64d4a24219f3df40f8bd2ef421cce4f573b4817793bd056c2ad8e2"},
		{Kind: "skill", Source: "bundle/skills/atomic-commit/SKILL.md", Target: "skills/atomic-commit/SKILL.md", SHA256: "6344323ed2ef86dbeb61b9ecbe4dc36723f14360413f8a506d2a7904cf1dc894"},
		{Kind: "skill", Source: "bundle/skills/atomic-debug/SKILL.md", Target: "skills/atomic-debug/SKILL.md", SHA256: "6b474fd0ed3c442868466c8d02abd26990e6eb1c5fe797b55d422eaec47d5e3a"},
		{Kind: "skill", Source: "bundle/skills/atomic-prose/SKILL.md", Target: "skills/atomic-prose/SKILL.md", SHA256: "1152e32ba1658562f72a03aa4ef88f5e938171a31d7dbb3bdf23bf231d8159d8"},
		{Kind: "skill", Source: "bundle/skills/atomic-review/SKILL.md", Target: "skills/atomic-review/SKILL.md", SHA256: "af782e3de92e97b4936d72f5a40ca17bd3fc4634e3ab49e97dce0732b8d2fc86"},
		{Kind: "skill", Source: "bundle/skills/atomic-signals/SKILL.md", Target: "skills/atomic-signals/SKILL.md", SHA256: "72097f1278d1df2032406df9972bf5a693bbc59c42e0480065a98af89d978412"},
		{Kind: "skill", Source: "bundle/skills/atomic-tdd/SKILL.md", Target: "skills/atomic-tdd/SKILL.md", SHA256: "c112fd537782b1388f0840a85ee80e3e78b9f38e2d28a469e3844fa1f884c75a"},
		{Kind: "skill", Source: "bundle/skills/atomic-verify/SKILL.md", Target: "skills/atomic-verify/SKILL.md", SHA256: "bacd131efb3cda4ecd618858df7a4b6f09107bab0c479959cadc9ca84cdfbaf3"},
	}
}
