/*
 * erlang_compat.c — compatibility shim for the tree-sitter-erlang grammar.
 *
 * WHY: tree-sitter-erlang was generated by a newer tree-sitter CLI that emits
 * `TSMapSlice` and `abi_version` identifiers. The tree-sitter runtime version
 * used here (ABI 14) uses the older names `TSFieldMapSlice` and `version`
 * respectively. The grammar's parse table is still ABI 14-compatible; only
 * these two preprocessor identifiers differ.
 *
 * Rather than applying -DTSMapSlice=TSFieldMapSlice -Dabi_version=version
 * globally (which would silently break any future grammar that legitimately
 * uses those identifiers with different semantics), we scope the renames here
 * and include the Erlang parser directly. The Makefile compiles this wrapper
 * instead of src/erlang/parser.c.
 *
 * src/erlang/parser.c is gitignored and fetched at build time by make fetch.
 */

#define TSMapSlice TSFieldMapSlice
#define abi_version version
#include "../src/erlang/parser.c"
