package followups

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// Render produces the INDEX.md content from entries and a reference date (today).
// Section order: 📋 plans → 🟡 risks → 🔵 nits → ❓ questions.
// Age is always in days. Stale = today > review_by.
// Plans are excluded from severity buckets.
func Render(entries []Entry, today time.Time) string {
	// Split by kind: plans go to their own section; findings go to severity buckets.
	plans := filterByKind(entries, KindPlan)
	findings := filterByKind(entries, KindFinding)

	// Bucket findings by severity.
	risks := filterBySeverity(findings, SeverityRisk)
	nits := filterBySeverity(findings, SeverityNit)
	questions := filterBySeverity(findings, SeverityQuestion)

	// Sort each bucket by id for deterministic output.
	sortEntries(plans)
	sortEntries(risks)
	sortEntries(nits)
	sortEntries(questions)

	// Compute stale count across all finding entries only (plans are exempt).
	staleCount := 0
	for _, e := range findings {
		if isStale(e, today) {
			staleCount++
		}
	}

	totalOpen := len(entries)
	lastRendered := today.Format("2006-01-02")

	var sb strings.Builder
	sb.WriteString("# Project follow-ups index\n")
	sb.WriteString("\n")
	sb.WriteString("Auto-generated by `atomic followups render`. Do not edit.\n")
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("Open: %d  •  Stale: %d  •  Last rendered: %s\n", totalOpen, staleCount, lastRendered))
	sb.WriteString("\n")

	writePlansBucket(&sb, plans)
	sb.WriteString("\n")
	writeBucket(&sb, "🟡 risks", risks, today)
	sb.WriteString("\n")
	writeBucket(&sb, "🔵 nits", nits, today)
	sb.WriteString("\n")
	writeBucket(&sb, "❓ questions", questions, today)

	return sb.String()
}

func writeBucket(sb *strings.Builder, label string, entries []Entry, today time.Time) {
	sb.WriteString(fmt.Sprintf("## %s (%d)\n", label, len(entries)))
	sb.WriteString("\n")
	if len(entries) == 0 {
		sb.WriteString("(none)\n")
		return
	}
	for _, e := range entries {
		ageStr := formatAge(ageInDays(e.Created, today))
		stale := isStale(e, today)
		var line string
		if stale {
			line = fmt.Sprintf("- [%s](%s.md) — %s (%s, **stale**)\n", e.ID, e.ID, e.Title, ageStr)
		} else {
			line = fmt.Sprintf("- [%s](%s.md) — %s (%s)\n", e.ID, e.ID, e.Title, ageStr)
		}
		sb.WriteString(line)
	}
}

func filterBySeverity(entries []Entry, sev Severity) []Entry {
	var out []Entry
	for _, e := range entries {
		if e.Severity == sev {
			out = append(out, e)
		}
	}
	return out
}

func filterByKind(entries []Entry, knd Kind) []Entry {
	var out []Entry
	for _, e := range entries {
		// Entries with an empty Kind are treated as KindFinding for back-compat
		// (direct struct construction in tests, pre-existing entries via ParseEntry).
		effective := e.Kind
		if effective == "" {
			effective = KindFinding
		}
		if effective == knd {
			out = append(out, e)
		}
	}
	return out
}

func writePlansBucket(sb *strings.Builder, entries []Entry) {
	sb.WriteString(fmt.Sprintf("## 📋 plans (%d)\n", len(entries)))
	sb.WriteString("\n")
	if len(entries) == 0 {
		sb.WriteString("(none)\n")
		return
	}
	for _, e := range entries {
		if e.File != "" {
			sb.WriteString(fmt.Sprintf("- [%s](%s.md) — %s → %s\n", e.ID, e.ID, e.Title, e.File))
		} else {
			sb.WriteString(fmt.Sprintf("- [%s](%s.md) — %s\n", e.ID, e.ID, e.Title))
		}
	}
}

func sortEntries(entries []Entry) {
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].ID < entries[j].ID
	})
}

// isStale returns true when today is strictly after review_by.
func isStale(e Entry, today time.Time) bool {
	// Plans are a backlog, not findings going cold — never stale.
	if e.Kind == KindPlan {
		return false
	}
	if e.ReviewBy == "" {
		return false
	}
	rb, err := time.Parse("2006-01-02", e.ReviewBy)
	if err != nil {
		return false
	}
	// Normalize today to midnight for day-level comparison.
	t := time.Date(today.Year(), today.Month(), today.Day(), 0, 0, 0, 0, time.UTC)
	return t.After(rb)
}

// ageInDays computes the number of days between created and today.
// Returns -1 if created is unparseable or is in the future (clock skew /
// typo); callers should render that as `?d` rather than silently masking
// the anomaly as `0d`.
func ageInDays(created string, today time.Time) int {
	c, err := time.Parse("2006-01-02", created)
	if err != nil {
		return -1
	}
	t := time.Date(today.Year(), today.Month(), today.Day(), 0, 0, 0, 0, time.UTC)
	days := int(t.Sub(c).Hours() / 24)
	if days < 0 {
		return -1
	}
	return days
}

// formatAge renders an age-in-days value for the INDEX. Negative values
// signal "unknown / future" and render as `?d` to surface the anomaly.
func formatAge(days int) string {
	if days < 0 {
		return "?d"
	}
	return fmt.Sprintf("%dd", days)
}
