package followups

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// Render builds INDEX.md against a reference date. Sections run plans, risks,
// nits, questions; age is in days and stale means today > review_by.
func Render(entries []Entry, today time.Time) string {
	plans := filterByKind(entries, KindPlan)
	findings := filterByKind(entries, KindFinding)

	risks := filterBySeverity(findings, SeverityRisk)
	nits := filterBySeverity(findings, SeverityNit)
	questions := filterBySeverity(findings, SeverityQuestion)

	// Sort by id so output is deterministic.
	sortEntries(plans)
	sortEntries(risks)
	sortEntries(nits)
	sortEntries(questions)

	staleCount := 0
	for _, e := range findings {
		if isStale(e, today) {
			staleCount++
		}
	}

	totalOpen := len(entries)
	lastRendered := today.Format("2006-01-02")

	var sb strings.Builder
	sb.WriteString("# Project follow-ups index\n")
	sb.WriteString("\n")
	sb.WriteString("Auto-generated by `atomic followups render`. Do not edit.\n")
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("Open: %d  •  Stale: %d  •  Last rendered: %s\n", totalOpen, staleCount, lastRendered))
	sb.WriteString("\n")

	writePlansBucket(&sb, plans)
	sb.WriteString("\n")
	writeBucket(&sb, "🟡 risks", risks, today)
	sb.WriteString("\n")
	writeBucket(&sb, "🔵 nits", nits, today)
	sb.WriteString("\n")
	writeBucket(&sb, "❓ questions", questions, today)

	return sb.String()
}

func writeBucket(sb *strings.Builder, label string, entries []Entry, today time.Time) {
	sb.WriteString(fmt.Sprintf("## %s (%d)\n", label, len(entries)))
	sb.WriteString("\n")
	if len(entries) == 0 {
		sb.WriteString("(none)\n")
		return
	}
	for _, e := range entries {
		ageStr := formatAge(ageInDays(e.Created, today))
		stale := isStale(e, today)
		var line string
		if stale {
			line = fmt.Sprintf("- [%s](%s.md) — %s (%s, **stale**)\n", e.ID, e.ID, e.Title, ageStr)
		} else {
			line = fmt.Sprintf("- [%s](%s.md) — %s (%s)\n", e.ID, e.ID, e.Title, ageStr)
		}
		sb.WriteString(line)
	}
}

func filterBySeverity(entries []Entry, sev Severity) []Entry {
	var out []Entry
	for _, e := range entries {
		if e.Severity == sev {
			out = append(out, e)
		}
	}
	return out
}

func filterByKind(entries []Entry, knd Kind) []Entry {
	var out []Entry
	for _, e := range entries {
		// An empty Kind means a finding, for entries predating the field.
		effective := e.Kind
		if effective == "" {
			effective = KindFinding
		}
		if effective == knd {
			out = append(out, e)
		}
	}
	return out
}

func writePlansBucket(sb *strings.Builder, entries []Entry) {
	sb.WriteString(fmt.Sprintf("## 📋 plans (%d)\n", len(entries)))
	sb.WriteString("\n")
	if len(entries) == 0 {
		sb.WriteString("(none)\n")
		return
	}
	for _, e := range entries {
		if e.File != "" {
			sb.WriteString(fmt.Sprintf("- [%s](%s.md) — %s → %s\n", e.ID, e.ID, e.Title, e.File))
		} else {
			sb.WriteString(fmt.Sprintf("- [%s](%s.md) — %s\n", e.ID, e.ID, e.Title))
		}
	}
}

func sortEntries(entries []Entry) {
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].ID < entries[j].ID
	})
}

func isStale(e Entry, today time.Time) bool {
	// A plan is a backlog, not a finding going cold.
	if e.Kind == KindPlan {
		return false
	}
	if e.ReviewBy == "" {
		return false
	}
	rb, err := time.Parse("2006-01-02", e.ReviewBy)
	if err != nil {
		return false
	}
	t := time.Date(today.Year(), today.Month(), today.Day(), 0, 0, 0, 0, time.UTC)
	return t.After(rb)
}

// ageInDays returns -1 for an unparseable or future created date, which callers
// render as `?d` rather than masking the anomaly as `0d`.
func ageInDays(created string, today time.Time) int {
	c, err := time.Parse("2006-01-02", created)
	if err != nil {
		return -1
	}
	t := time.Date(today.Year(), today.Month(), today.Day(), 0, 0, 0, 0, time.UTC)
	days := int(t.Sub(c).Hours() / 24)
	if days < 0 {
		return -1
	}
	return days
}

// formatAge renders a negative age as `?d`.
func formatAge(days int) string {
	if days < 0 {
		return "?d"
	}
	return fmt.Sprintf("%dd", days)
}
