// bundle-mirror copies the atomic-claude artifact bundle from the repo root into
// atomic/internal/embedded/bundle/ so the embed directive can reach it, and
// writes atomic/internal/embedded/manifest.go with the explicit allowlist.
//
// Run via: go generate ./... (from atomic/) or: go run ./cmd/bundle-mirror -repo <path>
//
// The output is deterministic: files are sorted, SHA256 is stable.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/damusix/atomic-claude/atomic/internal/bundlemirror"
)

// manifestTmpl generates manifest.go from the artifact list.
var manifestTmpl = template.Must(template.New("manifest").Parse(`// Code generated by cmd/bundle-mirror. DO NOT EDIT.
package embedded

// Artifact describes one file in the embedded artifact bundle.
type Artifact struct {
	Kind   string // "agent" | "command" | "skill" | "output-style" | "rule" | "claude-md"
	Source string // path inside the embedded FS, e.g. "bundle/agents/atomic-builder.md"
	Target string // path inside the target dir, e.g. "agents/atomic-builder.md"
	SHA256 string // hex-encoded SHA256 of the embedded source bytes
}

// Manifest returns the explicit allowlist of bundled artifacts.
// Generated at build time by cmd/bundle-mirror; commit the result.
func Manifest() []Artifact {
	return []Artifact{
{{- range .}}
		{Kind: "{{.Kind}}", Source: "{{.Source}}", Target: "{{.Target}}", SHA256: "{{.SHA256}}"},
{{- end}}
	}
}
`))

func writeManifest(outDir string, artifacts []bundlemirror.Artifact) error {
	manifestPath := filepath.Join(outDir, "manifest.go")
	f, err := os.Create(manifestPath)
	if err != nil {
		return fmt.Errorf("create manifest.go: %w", err)
	}
	defer f.Close()
	return manifestTmpl.Execute(f, artifacts)
}

func main() {
	var repoRoot string
	var outDir string
	flag.StringVar(&repoRoot, "repo", "", "path to repo root (parent of atomic/); defaults to ../ relative to cwd")
	flag.StringVar(&outDir, "outdir", "", "path to atomic/internal/embedded/; defaults to auto-detect")
	flag.Parse()

	wd, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "bundle-mirror: get cwd: %v\n", err)
		os.Exit(1)
	}

	if repoRoot == "" {
		repoRoot = filepath.Join(wd, "..")
	}

	repoRoot, err = filepath.Abs(repoRoot)
	if err != nil {
		fmt.Fprintf(os.Stderr, "bundle-mirror: resolve repo root: %v\n", err)
		os.Exit(1)
	}

	if outDir == "" {
		// Auto-detect: if cwd ends in "atomic", outDir = <cwd>/internal/embedded.
		// Otherwise fall back to <repoRoot>/atomic/internal/embedded.
		if strings.HasSuffix(filepath.ToSlash(wd), "/atomic") {
			outDir = filepath.Join(wd, "internal", "embedded")
		} else {
			outDir = filepath.Join(repoRoot, "atomic", "internal", "embedded")
		}
	}

	outDir, err = filepath.Abs(outDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "bundle-mirror: resolve outdir: %v\n", err)
		os.Exit(1)
	}

	artifacts, err := bundlemirror.Run(repoRoot, outDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "bundle-mirror: %v\n", err)
		os.Exit(1)
	}

	if err := writeManifest(outDir, artifacts); err != nil {
		fmt.Fprintf(os.Stderr, "bundle-mirror: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "bundle-mirror: wrote %d artifacts to %s\n", len(artifacts), outDir)
}
