package harness

import "regexp"

// providerPattern matches a concrete provider or model identifier. Every
// adapter's package generation rejects generated bytes that match it, so a
// provider choice cannot enter Atomic's output: Atomic stores semantic
// preferences and leaves the concrete selection to the user's configuration.
var providerPattern = regexp.MustCompile(`\b(?:openai|anthropic|google|azure|bedrock|vertex|ollama)/|\b(?:gpt|claude|gemini|llama|mistral|qwen|deepseek)-[0-9]`)

// ProviderID reports whether s names a concrete provider or model. A caller
// that wants a specific model sets it in its own native configuration.
func ProviderID(s string) bool { return providerPattern.MatchString(s) }
